// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuafaPlus.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuafaPlus.Migrations
{
    [DbContext(typeof(MuafaDbContext))]
    [Migration("20260405144345_Phase1_SeedTestInvitationCode")]
    partial class Phase1_SeedTestInvitationCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuafaPlus.Models.AssistantPhysicianLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssistantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhysicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("LinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AssistantId", "TenantId");

                    b.ToTable("AssistantPhysicianLinks");
                });

            modelBuilder.Entity("MuafaPlus.Models.GeneratedArticle", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("CoverageCodes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensInput")
                        .HasColumnType("integer");

                    b.Property<int>("TokensOutput")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("GeneratedArticles");
                });

            modelBuilder.Entity("MuafaPlus.Models.GenerationSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TotalArticles")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("SessionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("GenerationSessions");
                });

            modelBuilder.Entity("MuafaPlus.Models.InvitationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("TenantId");

                    b.ToTable("InvitationCodes");

                    b.HasData(
                        new
                        {
                            Code = "PH-TEST01",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "SYSTEM",
                            ExpiresAt = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Role = 2
                        });
                });

            modelBuilder.Entity("MuafaPlus.Models.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<string>("Comorbidities")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentMedications")
                        .HasColumnType("text");

                    b.Property<string>("MedicalRestrictions")
                        .HasColumnType("text");

                    b.Property<string>("PhysicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("PatientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MuafaPlus.Models.Physician", b =>
                {
                    b.Property<string>("PhysicianId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Yemen");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Credentials")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Arabic");

                    b.Property<bool>("SmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("PhysicianId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Physicians");

                    b.HasData(
                        new
                        {
                            PhysicianId = "PHY001",
                            City = "Sana'a",
                            Country = "Yemen",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.sana@hospital.ye",
                            EmailNotifications = true,
                            FullName = "Dr. Ahmed Al-Sana",
                            Institution = "Sana'a General Hospital",
                            IsActive = true,
                            LicenseNumber = "YE-MED-2018-001",
                            Phone = "+967-1-234567",
                            PreferredLanguage = "Arabic",
                            SmsNotifications = false,
                            Specialty = "Internal Medicine",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PhysicianId = "PHY002",
                            City = "Aden",
                            Country = "Yemen",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatima.hakim@clinic.ye",
                            EmailNotifications = true,
                            FullName = "Dr. Fatima Al-Hakim",
                            Institution = "Heart Care Clinic",
                            IsActive = true,
                            LicenseNumber = "YE-CARD-2019-042",
                            Phone = "+967-2-345678",
                            PreferredLanguage = "Arabic",
                            SmsNotifications = false,
                            Specialty = "Cardiology",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PhysicianId = "PHY003",
                            City = "Sana'a",
                            Country = "Yemen",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohammed.z@diabetes.ye",
                            EmailNotifications = true,
                            FullName = "Dr. Mohammed Al-Zubairi",
                            Institution = "Diabetes Center",
                            IsActive = true,
                            LicenseNumber = "YE-ENDO-2020-103",
                            Phone = "+967-1-456789",
                            PreferredLanguage = "Arabic",
                            SmsNotifications = false,
                            Specialty = "Endocrinology",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MuafaPlus.Models.PhysicianCredential", b =>
                {
                    b.Property<string>("PhysicianId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustResetOnNextLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PhysicianId");

                    b.ToTable("PhysicianCredentials");

                    b.HasData(
                        new
                        {
                            PhysicianId = "PHY001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MustResetOnNextLogin = true,
                            PasswordHash = "$2a$12$YA59.209V0gVCqlmF2Gu4.4ds.ETlKE/MMNT0PpTNQUQABUMbAf7i"
                        },
                        new
                        {
                            PhysicianId = "PHY002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MustResetOnNextLogin = true,
                            PasswordHash = "$2a$12$YA59.209V0gVCqlmF2Gu4.4ds.ETlKE/MMNT0PpTNQUQABUMbAf7i"
                        },
                        new
                        {
                            PhysicianId = "PHY003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MustResetOnNextLogin = true,
                            PasswordHash = "$2a$12$YA59.209V0gVCqlmF2Gu4.4ds.ETlKE/MMNT0PpTNQUQABUMbAf7i"
                        });
                });

            modelBuilder.Entity("MuafaPlus.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MuafaPlus.Models.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ChatEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("NotificationDelayHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("PatientChatWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("PatientNamePolicy")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppSenderId")
                        .HasColumnType("text");

                    b.HasKey("TenantId");

                    b.ToTable("TenantSettings");
                });

            modelBuilder.Entity("MuafaPlus.Models.TenantSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BillingCycleEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BillingCycleStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CasesAllocated")
                        .HasColumnType("integer");

                    b.Property<int>("CasesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("MuafaPlus.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "TenantId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MuafaPlus.Models.AssistantPhysicianLink", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", "Tenant")
                        .WithMany("AssistantPhysicianLinks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MuafaPlus.Models.GeneratedArticle", b =>
                {
                    b.HasOne("MuafaPlus.Models.GenerationSession", "GenerationSession")
                        .WithMany("GeneratedArticles")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationSession");
                });

            modelBuilder.Entity("MuafaPlus.Models.GenerationSession", b =>
                {
                    b.HasOne("MuafaPlus.Models.Patient", "Patient")
                        .WithMany("GenerationSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuafaPlus.Models.Physician", "Physician")
                        .WithMany("GenerationSessions")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("MuafaPlus.Models.InvitationCode", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", "Tenant")
                        .WithMany("InvitationCodes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MuafaPlus.Models.Patient", b =>
                {
                    b.HasOne("MuafaPlus.Models.Physician", "Physician")
                        .WithMany("Patients")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("MuafaPlus.Models.Physician", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MuafaPlus.Models.PhysicianCredential", b =>
                {
                    b.HasOne("MuafaPlus.Models.Physician", "Physician")
                        .WithOne()
                        .HasForeignKey("MuafaPlus.Models.PhysicianCredential", "PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("MuafaPlus.Models.TenantSettings", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("MuafaPlus.Models.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MuafaPlus.Models.TenantSubscription", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MuafaPlus.Models.UserRole", b =>
                {
                    b.HasOne("MuafaPlus.Models.Tenant", "Tenant")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MuafaPlus.Models.GenerationSession", b =>
                {
                    b.Navigation("GeneratedArticles");
                });

            modelBuilder.Entity("MuafaPlus.Models.Patient", b =>
                {
                    b.Navigation("GenerationSessions");
                });

            modelBuilder.Entity("MuafaPlus.Models.Physician", b =>
                {
                    b.Navigation("GenerationSessions");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MuafaPlus.Models.Tenant", b =>
                {
                    b.Navigation("AssistantPhysicianLinks");

                    b.Navigation("InvitationCodes");

                    b.Navigation("Settings");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
